apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-python-app
  template:
    metadata:
      labels:
        app: my-python-app
    spec:
      #securityContext:
      #  runAsNonRoot: true  # Fix for running container as non-root
      containers:
        - name: my-python-app
          image: 'GKE_REGION-docker.pkg.dev/PROJECT_ID/ARTIFACT_REGISTRY_REPO/IMAGE:TAG'
          securityContext:
            allowPrivilegeEscalation: false  # Fix for privilege escalation
          ports:
            - containerPort: 8080
