trigger:
  branches:
    include:
      - main
      - develop

pr:
  branches:
    include:
      - main
      - develop

variables:
  python.version: '3.10'

stages:
- stage: PreCommitChecks
  displayName: Pre-Commit Validation
  jobs:
  - job: RunChecks
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
      fetchDepth: 1

    - task: UsePythonVersion@0
      inputs:
        versionSpec: $(python.version)

    - script: |
        pip install pre-commit
      displayName: 'Install pre-commit'

    - script: |
        pre-commit run --all-files
      displayName: 'Run pre-commit hooks'
