name: Kubernetes Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pre_commit_scan:
    name: Check Kubernetes Manifests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Checkov (Kubernetes Security)
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: "./k8s-manifests"
          soft_fail: false

  container_scan:
    name: Scan Docker Image for Vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t my-app:latest .

      - name: Scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "my-app:latest"
          format: "table"
          severity: "CRITICAL,HIGH"
          exit-code: 1

      - name: Scan with Grype
        uses: anchore/scan-action@v3
        with:
          image: "my-app:latest"
          fail-build: true

  policy_check:
    name: Kubernetes Policy Enforcement
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run OPA Policy Check
        uses: open-policy-agent/setup-opa@v2
      - run: |
          opa eval --format pretty --data ./policies "data"

  cluster_security_scan:
    name: Kubernetes CIS Benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Install Kube-bench
        run: |
          curl -L https://github.com/aquasecurity/kube-bench/releases/latest/download/kube-bench-linux-amd64 -o kube-bench
          chmod +x kube-bench
          sudo mv kube-bench /usr/local/bin/

      - name: Run Kube-bench
        run: |
          kube-bench --config-dir `pwd`/cfg --json > results.json

      - name: Upload CIS Benchmark Report
        uses: actions/upload-artifact@v4
        with:
          name: kube-bench-report
          path: results.json

  runtime_monitoring:
    name: Deploy Falco for Runtime Security
    runs-on: ubuntu-latest
    steps:
      - name: Install Falco
        run: |
          curl -fsSL https://falco.org/script | sudo bash

      - name: Start Falco
        run: |
          sudo systemctl start falco
          sleep 30
          sudo journalctl -u falco --no-pager
